### ISSUE TITLE
ImportError: Using `bitsandbytes` 8-bit quantization requires Accelerate

### ISSUE THREAD

**Issue by MMIX2009** [leoneversberg/llm-chatbot-rag#1]
I tried the code, and I keep getting the following error despite installing the latest version of accelerate and bitsandbytes.I am running a virtual environment with Python 3.10.14 and all the other packages in requirements.txt.
Have you seen this issue?
ImportError: Using `bitsandbytes` 8-bit quantization requires Accelerate: `pip install accelerate` and the latest version of bitsandbytes:
`pip install -i https://pypi.org/simple/ bitsandbytes`

**Comment by leoneversberg** [comment]
To use quantization, you need a compatible graphics card.
You can check if your GPU is available in Python with
```
import torch
print(torch.cuda.is_available())
```
If you have an nvidia GPU but this prints False, you might need to install the CUDA toolkit first.

**Comment by MMIX2009** [comment]
Thanks for your prompt response.
I have an Nvidia GPU and the code returned False.
However, I did install the CUDA toolkit on my system before. Not sure, if this needs to be installed in the virtual environment, or if it is a one-time install for my whole system.

**Comment by gjnave** [comment]
Yes.. install cuda toolkit every time you create a new environment. But you
need to use conda. You also need to install pie torch after you've
installed cuda. Do a Google search for pie torch install and then find the
link.. installs a bunch of stuff

**Comment by MMIX2009** [comment]
Thank you for the feedback.

**Comment by hvjrocks-ds** [comment]
Hi,
I don't have a Nvidia Graphics card on my device, does that mean that it will not work on my system?

**Comment by leoneversberg** [comment]
Try running it on CPU.
You need to set `device="cpu"` and delete the `quantization_config` for the model.
