### ISSUE TITLE
Unable to run on local due to quantization error

### ISSUE THREAD

**Issue by Adnanmech** [leoneversberg/llm-chatbot-rag#2]
I'm getting this error :
ImportError: Using `bitsandbytes` 8-bit quantization requires Accelerate: `pip install accelerate` and the latest version of bitsandbytes: `pip install -i https://pypi.org/simple/ bitsandbytes`
Even after installing bitsandbytes and accelerate. any suggestion?

**Comment by leoneversberg** [comment]
#1 should answer your question
